import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import crypto from 'node:crypto';
import { ProjectsStore } from '../src/shared/projects';
import { validatePetPack } from '../src/shared/petpack';
import { sharpImageProbe } from '../src/main/image-probe';
import { exportWindowsZip } from '../src/main/export-win';
import { readRuntimeTemplate, runtimeSourceHash } from '../src/main/runtime-template';
import { createZip } from '../src/shared/zipw';
import { inspectZip, readZipEntry } from '../src/shared/zip';

const root = await fs.mkdtemp(path.join(os.tmpdir(), 'petstudio 离线 export '));
const previousPath = process.env.PATH;
try {
  const pack = await validatePetPack(path.resolve('assets/fixtures/pack-v2'), { probe: sharpImageProbe });
  assert.ok(pack.ok);
  const store = new ProjectsStore(path.join(root, 'data'));
  const meta = await store.importValidatedPack(pack.pack, { type: 'dir', path: pack.pack.rootDir });
  const templateDir = path.join(root, 'runtime-template');
  await fs.mkdir(templateDir);
  const names = ['PetLitePet.exe', 'resources/app/package.json', 'resources/app/main/main.js', 'resources/app/preload/petwin.js', 'resources/app/preload/sizeControl.js', 'resources/app/renderer/pet.html', 'resources/app/renderer/size-control.html', 'icudtl.dat', 'resources.pak', 'v8_context_snapshot.bin'];
  const template = createZip(names.map(name => ({ name, data: Buffer.from(name === 'resources/app/package.json' ? '{"main":"main/main.js"}' : 'runtime-fixture') })));
  const templatePath = path.join(templateDir, 'win-x64.zip');
  await fs.writeFile(templatePath, template);
  await fs.writeFile(templatePath + '.json', JSON.stringify({ schemaVersion: 1, productVersion: '0.2.0-beta.1', platform: 'win32', arch: 'x64', sha256: crypto.createHash('sha256').update(template).digest('hex') }));
  const identity = JSON.parse(await fs.readFile(templatePath + '.json', 'utf8'));
  await assert.rejects(readRuntimeTemplate(templatePath, root, '0.1.0'), /模板校验/);
  const sourceRoot = path.join(root, 'source');
  await fs.mkdir(path.join(sourceRoot, 'src/pet'), { recursive: true });
  await fs.writeFile(path.join(sourceRoot, 'src/pet/main.ts'), 'original');
  for (const file of ['electron.vite.pet.config.ts', 'package.json', 'package-lock.json']) await fs.writeFile(path.join(sourceRoot, file), '{}');
  await fs.writeFile(templatePath + '.json', JSON.stringify({ ...identity, sourceSha256: await runtimeSourceHash(sourceRoot) }));
  await readRuntimeTemplate(templatePath, sourceRoot, '0.2.0-beta.1');
  await fs.writeFile(path.join(sourceRoot, 'src/pet/main.ts'), 'updated');
  await assert.rejects(readRuntimeTemplate(templatePath, sourceRoot, '0.2.0-beta.1'), /源码不一致/);
  await fs.writeFile(templatePath + '.json', JSON.stringify(identity));
  process.env.PATH = '';
  const deps = { repoRoot: root, runtimeTemplatePath: templatePath, productVersion: '0.2.0-beta.1', onProgress() {} };
  const result = await exportWindowsZip(meta, store.projectDir(meta.id), root, deps);
  const bytes = await fs.readFile(result.zipPath);
  const entries = inspectZip(bytes).entries;
  const read = async (name: string) => readZipEntry(bytes, entries.find(e => e.name === name)!);
  assert.deepEqual(JSON.parse((await read('resources/petpack/config.json')).toString()), meta.config);
  assert.deepEqual(await read('resources/petpack/pet.json'), await fs.readFile(path.join(store.projectDir(meta.id), 'pet.json')));
  assert.deepEqual(await read('manifest.json'), await read('resources/manifest.json'));
  assert.ok(entries.some(e => e.name === 'runtime-integrity.json'));
  const second = await exportWindowsZip(meta, store.projectDir(meta.id), root, deps);
  assert.notEqual(result.zipPath, second.zipPath);
  assert.deepEqual(await fs.readFile(result.zipPath), bytes, 'previous export unchanged');
  await fs.appendFile(templatePath, 'corrupt');
  await assert.rejects(exportWindowsZip(meta, store.projectDir(meta.id), root, deps), /模板.*校验|模板.*损坏/);
  await fs.rm(templatePath);
  await assert.rejects(exportWindowsZip(meta, store.projectDir(meta.id), root, deps), /运行时模板/);
  console.log('PASS offline export: empty PATH, Unicode paths, content/config/integrity, no overwrite, corrupt/missing template');
} finally {
  if (previousPath === undefined) delete process.env.PATH; else process.env.PATH = previousPath;
  await fs.rm(root, { recursive: true, force: true });
}
